# Copyright 2022 Datum Technology Corporation
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
########################################################################################################################


[project]
name        = "uvma_clk"
full-name   = "Moore.io Clocking UVM Agent"
description = ""

[simulation]
preferred-simulators = [ "vivado" ]
